radix_notation : radix_notation.cc
	g++ -o radix_notation radix_notation.cc

draw_points : draw_points.cc
	g++ -o draw_points draw_points.cc

prime_factorization : prime_factorization.cc
	g++ -o prime_factorization prime_factorization.cc

reply_admin : reply_admin.cpp
	g++ -std=c++0x -o reply_admin reply_admin.cpp
